<?php

namespace App\Services;

use Illuminate\Support\Facades\Crypt;
use Illuminate\Contracts\Encryption\DecryptException;

class QrToken
{
    /**
     * Encode a document reference into an opaque, encrypted token for a QR
     * code. Only this application (holding APP_KEY) can decode it — a
     * regular camera app just sees meaningless text.
     *
     * Encoded as a short delimited string ("type|id") before encryption,
     * not JSON — full JSON keys ("type", "id", "issued_at") add unnecessary
     * bytes that make the encrypted output longer, which forces a denser,
     * harder-to-scan QR code once printed at a small physical size.
     */
    public static function encode(string $type, int $id): string
    {
        return Crypt::encryptString($type . '|' . $id);
    }

    /**
     * Decode a scanned token. Returns null if it's invalid, tampered with,
     * or wasn't generated by this application.
     */
    public static function decode(string $token): ?array
    {
        try {
            $raw = Crypt::decryptString($token);
        } catch (DecryptException $e) {
            return null;
        }

        $parts = explode('|', $raw, 2);

        if (count($parts) !== 2 || !is_numeric($parts[1])) {
            return null;
        }

        return ['type' => $parts[0], 'id' => (int) $parts[1]];
    }
}