<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\PotpotMayorsPermit;
use App\Models\Mtop;
use App\Models\TricycleMayorsPermit;
use App\Models\Franchise;
use App\Services\QrToken;
use Illuminate\Http\Request;

class ScannerController extends Controller
{
    /**
     * Maps a QR token's "type" to the model to look up and the fields
     * shown on the result card. Add new document types here as scanning
     * support grows — nothing else in the scanner needs to change.
     */
    protected function resolvers(): array
    {
        return [
            'potpot_mayors_permit' => [
                'model' => PotpotMayorsPermit::class,
                'label' => "Mayor's Permit — Potpot",
                'fields' => function (PotpotMayorsPermit $permit) {
                    return [
                        'Control No.' => $permit->control_no,
                        'Name' => $permit->name,
                        'Business Name' => $permit->business_name ?: 'None',
                        'Operation' => $permit->motorized_operation,
                        'Quarter' => $permit->quarter,
                        'Issue Date' => $permit->issue_date->format('M d, Y'),
                        'Expiry Date' => $permit->expiry_date->format('M d, Y'),
                        'OR No.' => $permit->or_no,
                        'Mayor' => $permit->mayor,
                    ];
                },
            ],
            'mtop' => [
                'model' => Mtop::class,
                'label' => 'MTOP',
                'fields' => function (Mtop $mtop) {
                    return [
                        'Case No.' => $mtop->case_no,
                        'Operator' => $mtop->tricycle->name ?? '—',
                        'Body No.' => $mtop->tricycle->body_number ?? '—',
                        'Route' => $mtop->route_operation,
                        'No. of Units' => $mtop->no_of_units,
                        'Date' => $mtop->date->format('M d, Y'),
                        'Officer-in-Charge' => $mtop->officer_in_charge,
                        'Mayor' => $mtop->mayor,
                    ];
                },
            ],
            'tricycle_mayors_permit' => [
                'model' => TricycleMayorsPermit::class,
                'label' => "Mayor's Permit — Tricycle",
                'fields' => function (TricycleMayorsPermit $permit) {
                    return [
                        'Control No.' => $permit->control_no,
                        'Owner' => $permit->tricycle->name ?? '—',
                        'Body No.' => $permit->tricycle->body_number ?? '—',
                        'Business Name' => $permit->business_name ?: 'None',
                        'Operation' => $permit->motorized_operation,
                        'Quarter' => $permit->quarter,
                        'Issue Date' => $permit->issue_date->format('M d, Y'),
                        'Expiry Date' => $permit->expiry_date->format('M d, Y'),
                        'OR No.' => $permit->or_no,
                        'Mayor' => $permit->mayor,
                    ];
                },
            ],
            'franchise_license' => [
                'model' => Franchise::class,
                'label' => 'License to Operate — Franchise',
                'fields' => function (Franchise $franchise) {
                    return [
                        'Authorized No.' => $franchise->authorized_no,
                        'Owner' => $franchise->tricycle->name ?? '—',
                        'Body No.' => $franchise->tricycle->body_number ?? '—',
                        'Plate No.' => $franchise->tricycle->plate_no ?? '—',
                        'Route' => $franchise->authorized_route,
                        'Valid Until' => $franchise->valid_until->format('M d, Y'),
                    ];
                },
            ],
        ];
    }

    public function index()
    {
        return view('admin.scanner');
    }

    public function verify(Request $request)
    {
        $request->validate(['token' => 'required|string']);

        $payload = QrToken::decode($request->input('token'));

        if (!$payload) {
            return response()->json([
                'ok' => false,
                'message' => 'This QR code is not valid or was not generated by this system.',
            ], 422);
        }

        $resolvers = $this->resolvers();
        $type = $payload['type'];

        if (!isset($resolvers[$type])) {
            return response()->json([
                'ok' => false,
                'message' => 'This document type is not supported by the scanner yet.',
            ], 422);
        }

        $resolver = $resolvers[$type];
        $record = $resolver['model']::find($payload['id']);

        if (!$record) {
            return response()->json([
                'ok' => false,
                'message' => 'This record no longer exists in the system.',
            ], 404);
        }

        return response()->json([
            'ok' => true,
            'label' => $resolver['label'],
            'status' => $record->status ?? null,
            'fields' => $resolver['fields']($record),
        ]);
    }
}