<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\PotpotMayorsPermit;
use App\Services\QrToken;
use Illuminate\Http\Request;

class ScannerController extends Controller
{
    /**
     * Maps a QR token's "type" to the model to look up and the fields
     * shown on the result card. Add new document types here as scanning
     * support grows — nothing else in the scanner needs to change.
     */
    protected function resolvers(): array
    {
        return [
            'potpot_mayors_permit' => [
                'model' => PotpotMayorsPermit::class,
                'label' => "Mayor's Permit — Potpot",
                'fields' => function (PotpotMayorsPermit $permit) {
                    return [
                        'Control No.' => $permit->control_no,
                        'Name' => $permit->name,
                        'Business Name' => $permit->business_name ?: 'None',
                        'Operation' => $permit->motorized_operation,
                        'Quarter' => $permit->quarter,
                        'Issue Date' => $permit->issue_date->format('M d, Y'),
                        'Expiry Date' => $permit->expiry_date->format('M d, Y'),
                        'OR No.' => $permit->or_no,
                        'Mayor' => $permit->mayor,
                    ];
                },
            ],
        ];
    }

    public function index()
    {
        return view('admin.scanner');
    }

    public function verify(Request $request)
    {
        $request->validate(['token' => 'required|string']);

        $payload = QrToken::decode($request->input('token'));

        if (!$payload) {
            return response()->json([
                'ok' => false,
                'message' => 'This QR code is not valid or was not generated by this system.',
            ], 422);
        }

        $resolvers = $this->resolvers();
        $type = $payload['type'];

        if (!isset($resolvers[$type])) {
            return response()->json([
                'ok' => false,
                'message' => 'This document type is not supported by the scanner yet.',
            ], 422);
        }

        $resolver = $resolvers[$type];
        $record = $resolver['model']::find($payload['id']);

        if (!$record) {
            return response()->json([
                'ok' => false,
                'message' => 'This record no longer exists in the system.',
            ], 404);
        }

        return response()->json([
            'ok' => true,
            'label' => $resolver['label'],
            'status' => $record->status ?? null,
            'fields' => $resolver['fields']($record),
        ]);
    }
}